version: "3"

services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btl-xla-nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "6001:6001"
    volumes:
      - .:/btl-xla-nodejs
      - node_modules:/btl-xla-nodejs/node_modules
    networks:
      - app-network
    command: npm start
