version: "3"

services:
  nodejs-server-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btl-xla-nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "6001:6001"
    command: npm start
